### ISSUE TITLE
Android Chrome: Hitting enter while an autocorrect is pending moves caret to start of line

### ISSUE THREAD

**Issue by hannesstruss** [ProseMirror/prosemirror#345] opened 2016-05-12 10:09 UTC
##### What I did:

1. Open prosemirror.net in Chrome Android (Nexus 5x, Android Marshmallow, Chrome 50.0.2661.89)
2. Place caret at end of paragraph
3. Hit enter, type "this is graet", hit Enter

Video: https://youtu.be/2PWtFQybzVs

##### What happened:

A new block was created, the spelling error was fixed, but the caret jumped to the beginning of the block I was typing.

##### What I expected to happen:

I'd expect the caret to jump to the newly created block.

cc @nickvelloff

**Comment by marijnh** [comment] 2016-06-06 13:52
The problem is caused by the way ProseMirror ties to map a post-input-event DOM selection to a ProseMirror selection -- in this case a text insertion and a newline (paragraph split) end up in a single input event, and the resulting mangled DOM nodes don't provide useful information about the corresponding ProseMirror document position.

I'll experiment with some alternative approaches to figuring out a selection position in a 'damaged' DOM structure.

**Comment by marijnh** [comment] 2016-06-07 09:37
This should be fixed now, with patches 3eb6a173b3...d89eb8348e3c38

**Closed by marijnh** 2016-06-07 09:37 UTC

**Comment by hannesstruss** [comment] 2016-06-07 09:38
Thanks! Will check it out asap.
