### ISSUE TITLE
[OS X] Broken when inserting via special characters pane

### ISSUE THREAD

**Issue by atg** [ProseMirror/prosemirror#96] opened 2015-12-04 15:58 UTC
1. Edit menu -> Emoji & Symbols
2. In a *new paragraph*, insert any character
3. The character is doubled, and prosemirror gets extremely confused:

`<p pm-path="2"><span pm-span="0-1">£</span>£</p>`

I don't know what's going on here, <strike>perhaps prosemirror is expecting every input to have a corresponding key event</strike> [edit: if you put a breakpoint in `handlers.input` you can see that the character has been inserted before the input event triggers, then applyDOMChange() inserts another one next to it]

Reproduced in Chrome, Safari, Firefox on OS X 10.11.0. Emoji doesn't seem to work at all on iOS but that may be a different issue.

**Comment by forresto** [comment] 2015-12-09 22:32
Related bug with the hold-key-for-accent interaction:
![pm-insert-accent](https://cloud.githubusercontent.com/assets/395307/11700951/d4aefc14-9e9a-11e5-9010-c31d2a89e9bb.gif)

**Comment by forresto** [comment] 2016-02-08 15:01
This looks fixed on http://prosemirror.net/ but not other demos and not my 0.3.0 version.

**Comment by marijnh** [comment] 2016-02-09 08:48
There was a fix (814c5da8e8326) related to this just before 0.3.0. I'm not aware of any patches since 0.3.0 that might have an influence on this.

**Comment by bergie** [comment] 2016-02-09 19:01
Possibly related: when typing individual characters, it works fine. But when using Android's swiping keyboard which enters full words, you get weird result: first entered word disappears when entering next one, and the next one is inserted in beginning of paragraph.

Can be reproduced in both ProseMirror and Ed demos.

**Comment by marijnh** [comment] 2016-02-11 14:03
Yeah, swiping keyboards generate very weird composition events. Patch 91af93b4dd2e solved one issue I ran into, but I noticed a bunch more (mostly showing up as random cursor jumping), which I did not manage to fix yet.

**Comment by marijnh** [comment] 2016-06-08 08:06
Could someone verify whether this still happens with the current master branch? The code that reads updates from the DOM, which is what will happen here, was much improved in the meantime.

**Comment by forresto** [comment] 2016-07-28 11:52
@marijnh emoji (from pane) and accented charaters (from hold) both seem to work fine now 👍 .

**Closed** 2016-07-28 20:33 UTC
