### ISSUE TITLE
Changes that are visually applied to the document, but that cause uncaught errors, lead to unpredictable editor behavior

### ISSUE THREAD

**Issue by kiejo** [ProseMirror/prosemirror#174] opened 2016-02-04 15:23 UTC
I have encountered this issue several times in different situations when using the editor, but it was always hard to find steps to reproduce this. Today, I finally found steps to reproduce the issue:

Create the following bullet list in the editor:

* a
* b
  * c

Then, select all text and press delete/backspace. This results in the expected visual changes to the document, but causes the following three uncaught errors in the console:
```
Uncaught Error: Offset -1 out of range
Uncaught Error: Offset 1 out of range
Uncaught Error: Failed to resolve path 0/1/1/0/0
```
If you continue typing in the editor, it throws many more errors in the console and leads to unpredictable behavior in the editor (e.g. jumping cursor, no autoinput, text markers do not work).

This is especially severe in cases where the document should be synced with a server or other collaborators as all the changes performed after the errors, do not trigger a mustSend event (applying the steps would probably fail anyway). This means that you continue typing until something unpredictable happens which is when you refresh the page and you lose your changes.

As I wrote in the beginning, I encountered the issue of uncaught errors related to document editing in different situations and the bullet list is only one concrete example of how I managed to reliably reproduce the issue.

I tested this using the 0.2.0 release as well as the version currently used on http://prosemirror.net.

Unfortunately, I do not know what the cause of these errors might be, but it looks like a lower level issue.

**Comment by marijnh** [comment] 2016-02-08 09:30
Crashing on bugs is intentional. These should be fixed, not wrapped in vague try/catch statements with shaky recovery strategies. The issue is the original exception, not the fact that it corrupts ProseMirror.

I can reproduce this and will look into it.

**Comment by kiejo** [comment] 2016-03-29 08:24
This has been fixed with the linear positions and rethought replace transforms. We can close this issue now.

**Comment by marijnh** [comment] 2016-03-29 08:25
Great!

**Closed by marijnh** 2016-03-29 08:25 UTC
