### ISSUE TITLE
Easy discovery of drag-move/copy-drop and property editing of images

### ISSUE THREAD

**Issue by rsaccon** [ProseMirror/prosemirror#184] opened 2016-02-07 01:14 UTC
when I select an image and then move it by drag/drop, the cursor shows the same green `+` icon as when I copy the image (without selecting it first). For moving I would expect the cursor to represent an icon which one associates with moving.

When I select an image, i can edit its properties, by clicking on insert / image in the tooltip. However "insert" suggests that one can insert something new and not edit what is currently selected. And all other tooltip options are not usable and just confusing, when an image is selected.  What about just directly showing the image property dialog, when one selects an image ?

**Comment by marijnh** [comment] 2016-02-08 09:45
> when I select an image and then move it by drag/drop, the cursor shows the same green + icon as when I copy the image

Which browser? Chrome and Firefox just show the image itself. This may be something that can be fixed with the [`dropEffect`](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/dropEffect) property, but I didn't know browsers actually looked at that.

As for the other thing (try to limit issues to a single issue), that looks like a duplicate of #157

**Comment by marijnh** [comment] 2016-06-08 07:59
Closing due to lack of followup info. (Feel free to continue commenting.)

**Closed by marijnh** 2016-06-08 07:59 UTC
