### ISSUE TITLE
Unexpected code block behaviors

### ISSUE THREAD

**Issue by kiejo** [ProseMirror/prosemirror#419] opened 2016-07-26 07:15 UTC
I noticed a few things when trying to work with `CodeBlocks` in ProseMirror:
- Pressing `Enter` at the end of a non-empty `CodeBlock` puts the cursor below the `CodeBlock`. I think it would be better to create a new line inside the code block by default. To leave a `CodeBlock` I would suggest pressing `Enter` in the last line if it is empty. This should then remove the empty line and put the cursor below the `CodeBlock` (like the `BlockQuote` behavior).
- Pressing `Shift-Enter` at the end of a non-empty `CodeBlock` creates a new `Paragraph` with two lines below the `CodeBlock`. I would suggest simply creating a new line inside the `CodeBlock` instead.
- Pasting text containing line breaks into a `CodeBlock`, only puts the first line into the `CodeBlock` and splits the rest of the pasted text into separate `Paragraphs`. This makes it impossible to copy and paste code from an editor into a ProseMirror `CodeBlock`. I would suggest putting all of the pasted content into the `CodeBlock` without doing any splitting.
- Pressing `Enter` in an empty `CodeBlock` moves the cursor below the `CodeBlock` with seemingly two lines. Focusing the `CodeBlock` and typing something turns it back into a single line. I would suggest turning the `CodeBlock` into a `Paragraph` in this case (like the `BlockQuote` and `ListItem` behavior).
- Pressing `Delete` at the end of a `CodeBlock` when below is a `Paragraph` containing a line breaks does nothing. I would suggest moving the `Paragraph` text content into the `CodeBlock`.
- Pressing `Delete` at the end of an empty `CodeBlock` when below is a `Paragraph`, replaces the `CodeBlock` with the `Paragraph`. I would suggest filling the `CodeBlock` with the text nodes of the `Paragraph`.

The first three problems make it super hard to work with `CodeBlocks` in ProseMirror. I think that copying and pasting code snippets is a major use case for `CodeBlocks` and improving this would make the experience so much better. Would be great to support these very basic editing features.

I'm also looking into embedding a full-fledged code editor inside ProseMirror instead of using `CodeBlocks`, but having these basic features might still be enough for many use cases and would also lower the need for the embedding of a full-fledged code editor.

**Comment by marijnh** [comment] 2016-07-26 07:59
For the first point, see the discussion in #222. It's not that easy (your solution would still be confusing when you try to create an empty line in a code block). Note that you're free to bind your own keys and are in no way obligated to use ProseMirror's defaults.

The others seem to be largely caused by the way hard_break nodes can't occur in code blocks, and thus ProseMirror will put them into paragraphs instead.

**Comment by kiejo** [comment] 2016-07-26 10:03
Thanks for the #222 reference, I'll create custom key bindings in this case.

As for the other issues it would probably be important to find a solution at some point if we want `CodeBlocks` to be usable. My current workaround to work with them is to create line breaks by putting the cursor somewhere in the middle of the text instead of at the end of the line.

**Comment by kiejo** [comment] 2016-07-28 13:22
I started implementing custom commands which allow the creation of an empty last line inside a `CodeBlock` and ran across the following problem: After hitting `Enter` to create the empty line the spacing is off, which seems to be caused by one of the two generated `br` tags.
![code1](https://cloud.githubusercontent.com/assets/152507/17213483/c2d9409e-54d4-11e6-8df9-0e83b01b25c8.png)
This is the HTML:
![pre_html](https://cloud.githubusercontent.com/assets/152507/17213498/cafcef96-54d4-11e6-86c3-1d4fd3523af3.png)

Starting to type something in the line brings the line spacing back to normal:
![code2](https://cloud.githubusercontent.com/assets/152507/17213494/c728c7b4-54d4-11e6-8938-0f2d7674d7b9.png)

I was able to fix the problem by rendering the code content directly into a `pre` tag without the additional `code` wrapper.
As I'm not exactly sure how the trailing breaks are supposed to work I thought I would bring this up, but fixing this by removing the `code` wrapper is OK for my use case.

**Comment by marijnh** [comment] 2016-12-02 21:25
The paste issue was resolved in 0.13.0, where pasting into code blocks started defaulting to doing a plain-text paste.

I've just pushed some patches that should address the other issues.

 - The `newlineInCode` command now also fires when at the end of a code block

 - There's a new command `exitCode` that's bound to mod-enter by default, which will create a new paragraph below a code block and jump into it.

 - When joining nodes with backspace/delete, if the first is empty, it is simply deleted. Otherwise, the second is joined onto the first as before, but any marks and nodes that aren't allowed in the first are dropped, so that joining a paragraph with a hard break onto a code block now works.

These introduce some incompatible changes, so I'll release them with 0.15.0 in a few weeks.

**Closed by marijnh** 2016-12-02 21:25 UTC
