### ISSUE TITLE
Editor freezes page when using the translate option of the Edge browser

### ISSUE THREAD

**Issue by yanmariomenev** [ProseMirror/prosemirror#1340] opened 2022-11-29 08:52 UTC
The Microsoft Edge browser's built-in translate tool (from the context menu) freezes the entire page if a ProseMirror editor is present in the DOM.

This behavior can be observed on the [ProseMirror ](https://prosemirror.net/)home page or in the Kendo UI Library [Editors ](https://www.telerik.com/kendo-angular-ui/components/editor/)that use ProseMirror.

If needed I can provide a runnable application and screen recording. 

Tested on Edge for Mac and Windows. Google Chrome translation doesn't seem to be affected and the page doesn't freeze.

**Screenshots**

![K85dYMRVp6](https://user-images.githubusercontent.com/49076727/204481141-e747590e-e524-45c2-9fdc-a3a7336ed033.png)
![msedge_EKPtaTn0Vj](https://user-images.githubusercontent.com/49076727/204481156-42ace8f2-4d9d-405b-bd4d-8dcbb20fa0c9.png)

**Comment by marijnh** [comment] 2022-11-29 10:57
This may be a loop between that tool messing with the editable DOM and ProseMirror fixing it up again. Frankly, I feel the blame for that is on the translation tool. Ideally, since they don't seem to respect the translate=no attribute, we'd find some other attribute to make them leave the content well enough alone. Have you searched for such a thing? Translating editable content is problematic for a number of reasons, but somehow these in-page translators don't seem to take that into account.

**Comment by marijnh** [comment] 2022-11-29 11:08
[Supposedly](https://learn.microsoft.com/en-us/azure/cognitive-services/translator/prevent-translation) Edge respects translate=no, making it even more strange that this is happening.

**Comment by yanmariomenev** [comment] 2022-11-29 16:25
I haven't done research on the matter, but it seems that the page crashing stops when the Editor is inside a div containing the `class="notranslate"` ([example](https://stackblitz.com/edit/angular-z4nd8c?file=src%2Fapp%2Fapp.component.ts)).

**Comment by marijnh** [comment] 2022-11-30 07:02
Odd. Could you see if adding an `attributes: {class: "notranslate"}` directly to the editor configuration also solves this? Maybe it is just picking up that, and not translate=no, despite claiming to support both.

**Comment by yanmariomenev** [comment] 2022-11-30 08:32
I did add the class directly to the kendo editor and the page still crashed. That is why I've placed it in a div containing the class and seems to work that way, which is kind of strange. It is also interesting that now I've added the `translate="no"` attribute directly to the kendo editor and the page doesn't crash.

          `<kendo-editor translate="no" [value]="value"></kendo-editor>`

**Comment by marijnh** [comment] 2022-11-30 11:41
I tried to reproduce this, but I don't see it happening. Edge translates the content outside of the editor, but leaves the editable text intact. Are you using a halfway recent version of ProseMirror that actually uses the translate=no attribute on the editable content?

**Comment by yanmariomenev** [comment] 2022-11-30 14:59
I am not very familiar with ProseMirror, but the versions that are used by the Editor are as follows:

"dependencies": {
    "prosemirror-commands": "1.3.1",
    "prosemirror-history": "1.3.0",
    "prosemirror-inputrules": "1.2.0",
    "prosemirror-keymap": "1.2.0",
    "prosemirror-model": "1.18.3",
    "prosemirror-schema-list": "1.2.2",
    "prosemirror-state": "1.4.2",
    "prosemirror-view": "1.29.1",
    "prosemirror-dropcursor": "1.6.1",
    "prosemirror-gapcursor": "1.3.1",
    "prosemirror-tables": "1.2.5",
    "prosemirror-transform": "1.7.0",
    "tslib": "^2.4.0"
  }

**Comment by marijnh** [comment] 2022-11-30 21:16
That's the current version, which definitely adds translate=no to its DOM element.

**Comment by yanmariomenev** [comment] 2022-12-01 08:47
It seems that both approaches that I've mentioned above aren't exactly working and the page still crashes. Not sure if this is fully related to the translation tool that Edge uses or if something else can be done on the ProseMirror side.

**Comment by marijnh** [comment] 2022-12-01 18:17
The first question then would be whether you can reproduce this on any page using ProseMirror, or only on yours.

**Comment by yanmariomenev** [comment] 2022-12-02 08:45
I was able to reproduce it on the [main page](https://prosemirror.net/) of ProseMirror where there is one editor for demonstration. Also crashes in the following standalone project - https://stackblitz.com/edit/react-prosemirror-editor-wpcko1?file=index.js
It isn't mine, but I manage to update it and reproduce the freezing when typing something in the editor and using the translation tool of Edge.

**Comment by marijnh** [comment] 2022-12-02 12:33
I can reproduce this in Edge 107, but the problem doesn't occur in Edge 89, which just cleanly translates text outside the editor and nothing more. So I'd say this is a regression in Edge, and I don't think ProseMirror can do anything about it. You could try reporting it to Microsoft.

**Comment by yanmariomenev** [comment] 2022-12-02 15:15
I've sent a report to the Microsoft Edge team via their feedback form. I will post any updates on their side here and maybe they will update us directly on this issue :)

**Comment by cxyguopong** [comment] 2022-12-09 09:01
**加粗**

**Comment by Young6118** [comment] 2022-12-13 12:22
我也遇到了这个问题

**Comment by ff0041** [comment] 2023-04-11 13:18
This was apparently fixed in Edge 112.0.1722.34.

**Comment by marijnh** [comment] 2023-04-11 13:19
That great to hear. Closing this issue.

**Closed by marijnh** 2023-04-11 13:19 UTC
