### ISSUE TITLE
Ipad: Could not change the position of the cursor

### ISSUE THREAD

**Issue by fh-schwarzh** [ProseMirror/prosemirror#159] opened 2016-01-29 19:05 UTC
If I want to change the position of the cursor and edit something in the existing text. The cursors stays at the end and I could just add new text.

**Comment by krasnoukhov** [comment] 2016-01-30 22:16
This looks like a duplicate of #145.

**Comment by marijnh** [comment] 2016-02-03 15:26
Agreed, it's a duplicate.

**Closed by marijnh** 2016-02-03 15:26 UTC
