### ISSUE TITLE
paste hr doesn't work

### ISSUE THREAD

**Issue by forresto** [ProseMirror/prosemirror#404] opened 2016-07-13 14:02 UTC
1. go to http://prosemirror.net/
2. insert horizontal rule
3. select it
4. cut (or copy)
5. make a new line
6. paste

Expected: horizontal rule pasted.

Actual: new line disappears. No errors in console.

**Comment by marijnh** [comment] 2016-07-26 08:00
I think this was a duplicate of #401.

**Closed by marijnh** 2016-07-26 08:00 UTC
