### ISSUE TITLE
Non-linear performance when pasting content

### ISSUE THREAD

**Issue by bradleyayers** [ProseMirror/prosemirror#364] opened 2016-05-31 01:38 UTC
I'm assessing the limits of ProseMirror from a performance perspective, and have found that overall things seem really good, however pasting large amounts of content degrades poorly.

_Scenario:_

Paste 300 lines, with each line containing 1,000 characters:

```
printf `printf '=%.0s' {1..1000}`'\n%.0s' {1..300} | pbcopy
```

On my computer it takes ~10 seconds. I also took some more samples to get a sense of the computational complexity:

![image](https://cloud.githubusercontent.com/assets/105820/15660782/00095780-2724-11e6-84fd-a271d65f2390.png)

I haven't profiled it to understand _why_ the algorithm behaves this way.

**Comment by marijnh** [comment] 2016-12-03 13:38
So, I've finally reached the point where I'm starting to look seriously at performance. Quadratic complexity is expected at this point (my data structure requires copying updated nodes, and if you make X changes each of which grows the size of the top node, that's quadratic). 10 seconds for 300 lines is very much not expected though.

I can't make much of your `printf` invocation, and 'lines' aren't really a concept in ProseMirror documents. Could you describe more precise instructions for reproducing this, or preferably a JS script that reproduces it?

I was initially planning to switch to a more complicated data structure for large nodes, which would sidestep this quadratic behavior, but my own benchmarks show the size-related node copying part of the cost of updates to be really small (JS array slicing seems to be done with a simple memcpy-ish operation) compared to the constant factors, so for now I'm leaning towards that complexity not being worth it.

**Comment by marijnh** [comment] 2016-12-03 16:02
(Ah, apparently `pbcopy` is an OS X thing to copy to the clipboard. So you're talking about pasting large chunks of text data. I can reproduce the slowness, but over 90% of the time is taken in updating the DOM, so I suspect it's a browser issue, not something ProseMirror can help. Will investigate further.)

**Comment by marijnh** [comment] 2016-12-03 16:09
Almost all of the time seems to be spent in updating the DOM selection, which I guess is the point at which the DOM layout gets computed. So I'm going to blame the browser for simply being slow to display such a large chunk of newly added text. (Lazy/viewport-only drawing is explicitly out of scope for ProseMirror, it gets good results in CodeMirror for situations like this -- I can do a paste like this in ~100ms there -- but it's _complicated_ to do in a non-intrusive way, even for flat, text-shaped content.)

So I'm going to close this as 'take it up with the browser'.

**Closed by marijnh** 2016-12-03 16:09 UTC
