### ISSUE TITLE
Need a way to specialize commands in the menu based on context

### ISSUE THREAD

**Issue by bZichett** [ProseMirror/prosemirror#336] opened 2016-05-09 18:47 UTC
Starting with the most basic indent list:

![1](http://i.imgur.com/L38x7Ql.png)

Press the de-dent command within the menu, while cursor is anywhere within the indented item.  You should get this:

![2](http://i.imgur.com/970N729.png)

Start from scratch (first picture) and then by pressing the keyboard shortcut for de-dent <kbd> ctrl-[ </kbd> proper behavior is applied, strangely enough:
![3](http://i.imgur.com/ZpwqR6U.png)

To get what the keyboard shortcut de-dent does using the menu button would require a lift twice, create indented list, and then join up but I certainly don't think that was intended.

Edit: Or Select Parent Block (esc) x2 and then lift...

* * * 

Using Google Chrome Version 50.0.2661.86 (64-bit) and the demo at https://prosemirror.net/demo/basic.html

**Comment by marijnh** [comment] 2016-05-09 19:16
You're using two different commands (`list_item:lift` versus the general `lift` command), which explains the different behavior. You can add the first to your menu if you want to make that available that way.

**Comment by bZichett** [comment] 2016-05-10 11:17
Then the ctrl-[ shouldn't be a label for 'lift' though?

**Comment by marijnh** [comment] 2016-05-10 11:20
The issue is that keys can be bound to several commands, based on context, whereas menu items don't have that. It's probably a good idea to support something like that for menu items.

**Comment by marijnh** [comment] 2016-06-07 16:08
I'm going to push this concern out of the core and onto people building their own menus -- the new concept of commands, which are just `(pm: ProseMirror, pm: apply) → bool` functions can be chained very easily, and defining menu items that chain them is similarly easy. Providing an automatic set of menu items and keybindings based on a schema is now out of scope for this library.

**Closed by marijnh** 2016-06-07 16:08 UTC
