### ISSUE TITLE
Native scrollIntoViewIfNeeded (or scrollIntoView, or any other scroll) is not working if decoration changes and scroll anchoring is not supported

### ISSUE THREAD

**Issue by matolg** [ProseMirror/prosemirror#1041] opened 2020-03-10 15:50 UTC
### Issue details

- I found this trying to implement find results highlight and navigation through them.
- In the plugin for this I'm trying to highlight find result with decoration and to scroll view to this result in view.update section.
- This is only true if browser do not supports scroll anchoring (like Safari do) so prosemirror tries to do this by its own
- This is crucial condition: _decoration change_ + _not supporting scroll anchoring_  + _native scroll_
- For Chrome there is this.dom.style.overflowAnchor supported, what skips prosemirror's anchoring behavior and relies on browser - everything works fine
- Safari in turn doesn't support scroll anchoring and prosemirror tries to restore scroll position even plugins tried to scroll manually through native scrollIntoView*

### Steps to reproduce

Please, check the demo
- There is scroll plugin that reacts on scroll command and trying to do both: highlight what to scroll to and to perform native scroll.
- In decoration there is randomisation part just to imitate constantly changing decorations; in real life this is floating decoration that moves from one find result entry to another.

Demo: https://glitch.com/edit/#!/lava-half-wallflower?path=index.js:1:2

### ProseMirror version

- prosemirror-view: 1.11.2

### Affected platforms

- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [x] Mac Safari, iOS Safari
- [ ] Other

### Screenshots / Screencast (Optional)

**Chrome - OK**
![Kapture 2020-03-10 at 18 23 15](https://user-images.githubusercontent.com/1191920/76330092-773e2c80-62fe-11ea-81e4-8bc3cc131482.gif)

**Safari - not OK**
![Kapture 2020-03-10 at 18 24 17](https://user-images.githubusercontent.com/1191920/76330043-62fa2f80-62fe-11ea-8da5-c67ae527d81f.gif)

**Comment by matolg** [comment] 2020-03-10 16:38
Probably, we need to just check selection change here and do not involve decorations..
https://github.com/ProseMirror/prosemirror-view/blob/c29d8f3d483b96304520d09f57afa64fd1178d2b/src/index.js#L135

**Comment by marijnh** [comment] 2020-03-12 17:19
There's quite a lot of confusion in your code — a line like `view.state.tr.setMeta("scroll", false)` will have exactly zero side effects. As for `state.view = view`, _no_, just don't do that. Your plugin state update methods should never have side effects.

In general, this is, firstly, too much of an abuse of the library for me to want to debug it, and secondly, on the surface sounds more like a Safari issue than a ProseMirror issue. So I'm going to close this, but if you can reduce the problem to a piece of code that doesn't misuse the library in ways the docs disallow and shows that the problem is actually in ProseMirror itself, feel free to add another comment.

**Closed by marijnh** 2020-03-12 17:19 UTC

**Comment by jljorgenson18** [comment] 2020-03-12 23:49
@marijnh To illustrate a scenario where this actually becomes a problem is scrolling to decorations when decorations are set through the document. We have a find and replace plugin that toggles through the various matches and scrolls to them. The matches are "decorated" and you toggle to the "primary" decoration when the primary decoration changes. If you scroll in the view update function (which I believe was for side effects and this is a dom interaction), then the scroll is immediately reset on Safari because of overflowAnchor check. We had to get around this by scrolling in a setTimeout.

**Comment by marijnh** [comment] 2020-03-13 06:39
> This not work in Safari because the updatePluginViews fires before the scroll handling

Maybe just delay the scroll behavior in a `requestAnimationFrame`? Or register a `handleScrollToSelection` function that returns true when your plugin already did scrolling on this update?

**Comment by matolg** [comment] 2020-03-13 09:48
Yep, `requestAnimationFrame` is how we solved this, but this still workaround, normally it shouldn't be needed.
Solution with adding `handleScrollToSelection` won't work as is because it need scroll to be "to selection" and this happens only after tr.scrollIntoView(), but actually highlighted find result is not a selection.
And again, this is just a workaround.

The question is why it works fine in Chrome but don't in Safari.
And the answer is: _Safari do not support overflowAnchor_.
And it is OK for client to not to support some feature.
PM don't act correctly in case of client don't support this feature what is not OK.

**Comment by jljorgenson18** [comment] 2020-03-13 14:44
`handleScrollToSelection` doesn't seem like the right option because we are not scrolling to a selection and it requires additional properties on a transaction.

Working around this issue is easy with a rAF or a setTimeout, but it's just a slight inconsistency and could confuse other users.

Another thing to point out is that `updateSel` is true because `updateDoc` is true when the decorations change. If there was another flag along the lines of `onlyDecorationsUpdated`, then we could  skip setting `oldScrollPos` when that flag is true.
