### ISSUE TITLE
Editor freezes browser after few changes in IE11@Win7

### ISSUE THREAD

**Issue by katemihalikova** [ProseMirror/prosemirror#288] opened 2016-03-31 12:05 UTC
We are testing ProseMirror in IE11 now and strange bug appears:
- navigate to a page with ProseMirror
- editor works fine when trying various features
- after a moment (few menu buttons clicks) the browser is not responding to clicks (neither in editor nor in the rest of the page nor anywhere else including browser UI), but keyboard is still active, editor still works, text can be typed and features can be used via key bindings (`ctrl+B` etc.)
- no error is shown in console
- `ctrl+R` reloads page and the browser returns to normal

**Version:** Both [demo editor](http://prosemirror.net/demo/basic.html) and custom v0.5.1 editor
**Not working:** IE11@_Win7_ (versions 11.0.14, 11.0.27, 11.0.29)
**Working fine:** IE11@_Win10_ (version 11.0.29), Edge@Win10, Chrome

**Comment by katemihalikova** [comment] 2016-04-01 12:27
I've filed an [IE11 bug](https://connect.microsoft.com/IE/feedbackdetail/view/2538977/ie11-win7-prosemirror-editor-freezes-browser) to help resolve this.

**Comment by marijnh** [comment] 2016-04-05 09:51
I was able to reproduce this, but the debugger only kept pointing at the first line of the selection poller callback. Adding console.log statements there showed that it was still being called, repeatedly as normal. So it seems the script was still running, more or less as normal. In one instance, I was still able to type into the editor. But mouse input was ignored. So this seems to be IE getting into some pathological state where 'the mouse breaks'. Does suggest an IE bug, but I doubt they'll respond quickly to a bug report that depends on a big library.

**Comment by katemihalikova** [comment] 2016-04-05 09:55
Thanks for the investigation. Surprisingly, they responded fairly quickly:

> Please note that we are not working on IE feature bugs any longer unless they are security related. As such, this item will be closed out as a Won't Fix item to reflect this.

**Comment by marijnh** [comment] 2016-04-05 10:25
I'm not sure an automated wontfix is what we were hoping for 😕. I guess if we decide to try and support IE11/Win7 we'll have to dig into this ourselves and see exactly which behavior triggers this bug. For now, this isn't a priority for me.

**Comment by marijnh** [comment] 2017-01-30 13:30
@katemihalikova Could you see if you're still able to reproduce this with recent ProseMirror versions? I haven't ran into it anymore, and enough changed that maybe we're not doing anymore whatever it was that was triggering this.

**Comment by marijnh** [comment] 2017-02-18 21:59
Closing this until further information comes in.

**Closed by marijnh** 2017-02-18 21:59 UTC

**Comment by katemihalikova** [comment] 2017-03-08 21:23
I've just tried to break the demo page in *IE11.0.14@Win7* and it works fine so far. I don't have the other versions on hand anymore though..
