### ISSUE TITLE
Wrong caret position after inserting an atom node on safari

### ISSUE THREAD

**Issue by Violeta-Amza** [ProseMirror/prosemirror#1185] opened 2021-06-23 10:18 UTC
### Issue details

The caret position is wrong after inserting an atom node.

### Steps to reproduce

Starting from the Dino example(https://prosemirror.net/examples/dino/)

1. delete the entire content
2. write a simple text and insert a dino node.

As you can see in the attached picture, the caret position is at the beginning of the current line.
![Screenshot 2021-06-23 at 13 05 00](https://user-images.githubusercontent.com/32900172/123078745-eff9c700-d423-11eb-9661-f77d6a133589.png)

Notes:
If I write something after the node dino is inserted, it adds the text after the dino node as it should.

### ProseMirror version
latest 

### Affected platforms

- [ ] Safari

**Comment by marijnh** [comment] 2021-06-23 10:21
Is this a duplicate of https://github.com/ProseMirror/prosemirror/issues/1165? When you say latest, does that mean you're using prosemirror-view 1.18.8?

**Comment by Violeta-Amza** [comment] 2021-06-23 10:43
Yes, it seems to be a duplicate of #1165.  I tested with loaded version from website examples and I assumed that are the latest but there are not, sorry for that.

**Comment by marijnh** [comment] 2021-06-23 10:49
Great, closing.

**Closed by marijnh** 2021-06-23 10:49 UTC
