### ISSUE TITLE
Android: Cursor should not jump back to previous location when autocorrection is enabled and text length at new location does not match the previous

### ISSUE THREAD

**Issue by owjsub** [ProseMirror/prosemirror#552] opened 2017-02-03 19:52 UTC
![](https://raw.githubusercontent.com/owjsub/prosemirror-gif-repro/master/0.17.3/android-chrome-cursor-position-issue/repro.gif)

ref: http://prosemirror.net/demo/basic.html
reproduced on Android 6.0.1 Chrome

**Comment by marijnh** [comment] 2017-02-03 20:11
What is actually happening here? You appear to be enabling and disabling some browser settings, but I'm not sure what 'text length at new location' and 'previous' refer to.

**Comment by owjsub** [comment] 2017-02-03 20:14
In the GIF at the beginning, suggestions/autocorrect are enabled then I tap on the word "text". The cursor incorrectly jumps back to "styling".

**Comment by owjsub** [comment] 2017-02-03 20:27
In the GIF at the end, i disabled suggestions/autocorrect, then the cursor correctly switches from the word "text" (the prev location) to the word "styling" (the new location).

**Comment by owjsub** [comment] 2017-02-06 20:44
See updated GIF above ^

**Comment by jonsutherland** [comment] 2017-09-02 03:08
Hi, I appreciate the effort on this great product however I'd like to draw attention to this issue.  Currently it seems to be the only show stopper preventing us from rolling prosemirror out as an internal web app within WebView for our Android application. 

I can't really comment on the cause just yet but it seems to be related to string replacements made by the keyboard, maybe undetected by prosemirror. I won't speculate further but I will try to come up with some concrete information on when, where, and how this is happening since it's still occurring last I checked about a week ago. 

Thanks much

**Comment by marijnh** [comment] 2017-09-05 13:21
I still don't understand the issue, so if you want me to look at this, a **textual** description of the problem, without any blinking inscrutable gifs, would be very helpful. Also mention which screen keyboard you are using. With Gboard, letting autocorrect kick in seems to work just fine.

**Comment by owjsub** [comment] 2017-09-10 04:54
@marijnh I am no longer able to reproduce the issue on Android 6.0.1 in Chrome using Gboard v6.4.16.162469584

I'm not sure what version of Gboard I was using previously, but here are the steps I used to reproduce the issue:
- Open ProseMirror basic example on Android 6.0.1 in Chrome using Gboard
- In keyboard settings, enable Suggestions + Auto correction
- Tap on the word "styling"
- Tap on the word "text" (observe cursor briefly move to the word "text", then quickly jump back to the word "styling"

**Comment by jonsutherland** [comment] 2017-09-10 15:36
Yeah seems like Gboard that I updated to just recently in Oreo fixed the
issue. Sorry and thanks again.

**Comment by marijnh** [comment] 2017-09-10 16:28
I tested on Android 6, so I guess it's a Gboard update that also gets pushed to older versions. Going to close this, but feel free to reopen/append when you do run into it again.

**Closed by marijnh** 2017-09-10 16:28 UTC
