### ISSUE TITLE
Arrow keys moves cursor to unexpected positions

### ISSUE THREAD

**Issue by mirrec** [ProseMirror/prosemirror#702] opened 2017-10-04 12:21 UTC
Hello,

first of all, ProseMirror looks awesome! Great work!

### Issue details

In text editor, when you put your cursor on some possition (1st row, 10th character), and you press arrows down or up, row number changes. But character / column  number should keeps the same (if it is possible). If it is not possible (line below or above is shorter) it should goes to the end of the line, and get back to the 10th character on some next line, when possible (line is long enough).

This is not the case in ProseMirror.

I made a [screencast](https://www.youtube.com/watch?v=02J-9QpAqIM) to describe problems. I hope it will help. Basically there are 3 issues. Here is text description.

1. Cursor is not keeping column on different lines. (all tested browsers)
2. When there is empty paragraph 'on the way' from up to down, cursor moves to beginning of paragraph, even it should follow character number. (chrome, safari and IE)
3. Cursor jumps to unexpected position when we are on the first or last line of document (chrome and safari)

#### Issue 1

> Cursor is not keeping column on different lines.

1. open prosemirror.net in Chrome
2. copy & paste this text to the editor

```
Like this one!
short text
Try it out by typing in here or see more examples.
```

3. Put cursor on the last line after 4th character: 'Try <CURSOR>it'
4. Press arrow up, and you will be on the 3rd character of previous line: 'sho<CURSOR>rt'. Eventhough it should be on the 4th character.
5. So cursor is now at 3rd character at 'sho<CURSOR>rt'.
6. When you press arrow up key, you get to the first line, but to the 4th character: 'Like<CURSOR>'.

#### Issue 2

> Empty paragraph break keeping column position on the way down

1. open prosemirror.net in Chrome
2. copy & paste this text to the editor

```
Like this one!
short text
Try it out by typing in here or see more examples.
```

3. add empty line after second line, so text should look like this

```
Like this one!
short text

Try it out by typing in here or see more examples.
```
(I am not able to copy & paste empty line, so it has to be done manualy)

4. put your cursor to the end of the first line: '...one!<CURSOR>'
5. press down arrow key 3 times, and you end on last line with cursor on before first character: '<CURSOR>Try'. Even though it should be here: 'by <CURSOR>typing'

#### Issue 3
> Cursor jumps to unexpected position from first or last line of document

1. open prosemirror.net in Chrome
2. copy & paste this text to the editor

```
Like this one!
short text
Try it out by typing in here or see more examples.
```

3. put your cursor to the end of the first line: '...one!<CURSOR>'
4. press arrow up: it will put cursor to the beginning of the first line (this is correct): '<CURSOR>Like'
5. now press arrow down, and get to the end of the first line '...text<CURSOR>'. You should be on the beginning of this line.

### Please specify which version of ProseMirror you're running

ProseMirror v 0.24

### Affected platforms

- [x] Chrome 60
- [x] Firefox 56
- [x] Safari 10.1.1
- [x] Internet Explore 11

### Screencast (Optional)

https://www.youtube.com/watch?v=02J-9QpAqIM

**Comment by marijnh** [comment] 2017-10-04 14:15
Issue 1 is the intended behavior. Vertical behavior is based on screen position, not column count. This is how every rich text editor I'm aware of works, and ProseMirror is letting the browser control the selection, including arrow-key movement, so we get what the browser implements.

Issue 2 should be fixed by patch 446c3c3.

Issue 3 is a Chrome bug (you get it in any contentEditable content, even without ProseMirror), so that's best reported in Chrome's issue tracker. It doesn't seem severe enough to add a specific workaround to ProseMirror in the meantime.

**Closed by marijnh** 2017-10-04 14:15 UTC

**Comment by mirrec** [comment] 2017-10-04 14:42
@marijnh thanks for a quick response!

Can you suggest workaround for issue 3? Because it looks like I am not able to use custom `SelectionReader`. Thanks a lot.

**Comment by marijnh** [comment] 2017-10-04 14:47
You could detect the situation where arrow-up puts the cursor at the start of the document (in a keyup handler, possibly), and reset the DOM selection at that point (clear it and reset it to its old range) to make it forget about the previous vertical position.

**Comment by MolloKhan** [comment] 2023-02-03 16:25
> You could detect the situation where arrow-up puts the cursor at the start of the document (in a keyup handler, possibly), and reset the DOM selection at that point (clear it and reset it to its old range) to make it forget about the previous vertical position.

Hey @marijnh perhaps this may help you. I solved this by adding a `keydown` event, then, if the up/down key is pressed I call `ev.preventDefault()` - it worked like a charm in my situation
