### ISSUE TITLE
History plugin throws exception on undo with no remaining undo states

### ISSUE THREAD

**Issue by andersonmat** [ProseMirror/prosemirror#481] opened 2016-10-28 21:25 UTC
I'm using `prosemirror-history` and `prosemirror-keymap` as seen on the [basic editor guide](http://prosemirror.net/guide/basics.html) page and am seeing the following exception when attempting to undo after there are no more undo states on the stack:

```
Uncaught TypeError: Cannot read property 'transform' of null
    at histAction (history.js:309)
    at undo (history.js:368)
    at Plugin.handleKeyDown (keymap.js:81)
    at input.js:44
    at EditorView.someProp (index.js:155)
    at dispatchKeyDown (input.js:44)
    at handlers.keydown (input.js:51)
    at HTMLDivElement.<anonymous> (input.js:35)
```

**Comment by marijnh** [comment] 2016-10-29 11:46
This is a duplicate of #479, which is fixed by https://github.com/ProseMirror/prosemirror-history/commit/685a1a459c91044c8eee3275f1c12331627ef2b2

**Closed by marijnh** 2016-10-29 11:46 UTC

**Comment by andersonmat** [comment] 2016-10-29 18:41
Hmm, I'm running with the latest off of npm (0.12.0) and am getting this. I assume 685a1a4 went out with 0.12.0 on npm?

**Comment by marijnh** [comment] 2016-10-29 22:53
No, it's not in 0.12.0 yet. I'll bring out a new release next week.
