### ISSUE TITLE
Replacing slice by itself throws TransformError: Invalid content for node

### ISSUE THREAD

**Issue by thomasgafner** [ProseMirror/prosemirror#1062] opened 2020-05-27 08:14 UTC
### Issue details

My expectation: Any 
slc = doc.slice(..)
tr.replace(.., slc)
will allways work, if the positions are the same for both commands.

### Steps to reproduce

I extended the default schema by a 'tuple' - kind of a table of fixed size: just one row and two columns.
The first cell I call flow-normal and the second cell I call flow-reverse.
I added:

sym_tup_div: {
	content: "p_sym_tup_flow_normal p_sym_tup_flow_reverse",
	group: "block",
	defining: true,
	parseDOM: [{tag: "div.symmetry-tuple"}],
	toDOM() { return ["div", {class: "symmetry-tuple"}, 0] }
},
span_sym_tup_flow_normal: {
	content: "limited_inline*",
	defining: true,
	parseDOM: [{tag: "span.flow-normal",context: "sym_tup_div/"}],
	toDOM() { return ["span", {class: "flow-normal"}, 0] }
},
span_sym_tup_flow_reverse: {
	content: "limited_inline*",
	defining: true,
	parseDOM: [{tag: "span.flow-reverse",context: "sym_tup_div/"}],
	toDOM() { return ["span", {class: "flow-reverse"}, 0] }
},

(I would have used a similar nested structure of the basic schema to show how to reproduce the bug, but I think there is no such.)

Then my intention was to have a transform, that when the cursor is inside the flow-normal (first cell) of the tuple, that transform takes the remaining part of the flow-normal and moves that to a new paragraph after. I can achieve that by replacing the whole tuple by one with the shortened flow-normal and a new paragraph after, but I wanted the positions involved in the replace to be as narrow as possible, because the content can also be very large.
So I started slicing the tuple inside the flow-normal resulting in a (2,0) open start/end slice - instead of a (0,0) one. When replacing by my modified (2,0) slice I encountered some trouble and I started debugging my code. Even after a while not finding what is wrong (My before and after tuple positions are correct.), I decided to simply replace by what I slice, without changing it - just for testing. And now I find that not working either.

My expectation to any slc = doc.slice(..) tr.replace(.., slc) was, that it will allways work, at any same positions.

What I do:
Transform.prototype.doMyThing = function() {
	let doc = this.doc;
	let selection = this.selection;
	let tr = this;
	const before = ..
	const after = ..
	const srcSlc = doc.slice(selection.to, after)
	tr = tr.replace(selection.from, after, srcSlc)
	return tr
}

In my case for testing I move the cursor inside the flow-normal span (not the very start nor the very end) and trigger the transform. So selection.from == selection.to.
It should actually happen nothing, because I replace what is there with what was there before.

srcSlc.toString()
<sym_tup_div(
	p_sym_tup_flow_normal("neglegentur pro."), 
	p_sym_tup_flow_reverse("An alitr ansequat quaerendum nec."))
>(2,0)

But I get: 
TransformError: Invalid content for node sym_tup_div load.js line 68 > eval:274:19
    TransformError http://../moduleserve/load.js line 68 > eval:274
    step http://../moduleserve/load.js line 68 > eval:314
    replace http://../moduleserve/load.js line 68 > eval:1160
    doMyThing myModule.js:1951
    ..   

### ProseMirror version

prosemirror-transform 1.2.5
prosemirror-model 1.10.0
(just pulled every module anew and rebuilt)

### Affected platforms

Firefox Browser 76.0.1 (64-Bit)
Google Chrome Version 81.0.4044.113 (Official Build) (64-Bit)

### Screenshots / Screencast (Optional)

I've started digging a bit into the code where it happens, and I found in model/src/replace.js the close function, which I modified to see what it is exactly complaining about:

function close(node, content) {
  if (!node.type.validContent(content)) {
		console.log('invalid', node.toString(), content.toString())
		throw new ReplaceError("Invalid content for node " + node.type.name)
	}
  return node.copy(content)
}

The output: invalid
node.toString():
sym_tup_div(
	p_sym_tup_flow_normal("Arem apsum dolor sit amet, sea graeci timeam antiopam an, eius ludus ad mei, et case efficiantur neglegentur pro."),
	p_sym_tup_flow_reverse("An alitr ansequat quaerendum nec.")
) 
content.toString():
<
p_sym_tup_flow_normal("Arem apsum dolor sit amet, sea graeci timeam antiopam an, eius ludus ad mei, et case efficiantur neglegentur pro."), 
p_sym_tup_flow_reverse, 
p_sym_tup_flow_reverse("An alitr ansequat quaerendum nec.")
>

From the output of content it is clear to me the content won't fit into the node, because two times p_sym_tup_flow_reverse is not allowed in the schema.
But what is the reason for that empty flow-reverse? The slice is just replaced by itself. - Why can't it just fit where it has been?

On the other hand: If I slice before to after then the slice is:
srcSlc 
<sym_tup_div(
	p_sym_tup_flow_normal("Arem apsum dolor sit amet, sea graeci timeam antiopam an, eius ludus ad mei, et case efficiantur neglegentur pro."), 
	p_sym_tup_flow_reverse("An alitr ansequat quaerendum nec."))
> (0,0)
and replacing works fine.

I also tried tr.replaceRange(..) instead, but it is the same.

So I finally thought: It is a bug in the framework.

**Comment by marijnh** [comment] 2020-05-27 08:30
Does `doc.check()` on the initial document go through without error? If it does, then replacing a range with its own slice should indeed work. Can you set up a minimal self-contained script that allows me to reproduce the issue?

**Comment by thomasgafner** [comment] 2020-05-27 09:13
The document I am working with is the one used in a running editor instance. Many other transforms are working on it correctly, when using the editor. My schema always seemed to be valid and working in other cases. - As I said, when I replace the whole sym_tup_div by a variation of it and an additional paragraph then the replace is valid.
I just added a doc.check() in the doMyThing transform just before doing doc.slice(..) and there is no exception thrown.
I have already reduced my example as much as I could think of in a first step. - My setup is actually more complex. - But I try to provide you a more self-contained script.

**Comment by thomasgafner** [comment] 2020-05-27 11:05
While preparing a more-selfcontained example I found, that I copy-pasted the wrong parts of the schema into the example above: Instead of span_sym_tup_flow_normal/reverse it should have been:

p_sym_tup_flow_normal: {
	content: "inline*",
	defining: true,
	parseDOM: [{tag: "p.flow-normal", context: "sym_tup_div/"	}],
	toDOM() { return ["p", {class: "flow-normal"}, 0] }
},
p_sym_tup_flow_reverse: {
	content: "inline*",
	defining: true,
	parseDOM: [{tag: "p.flow-reverse", context: "sym_tup_div/" }],
	toDOM() { return ["p", {class: "flow-reverse"}, 0] }
},
- just for correctness.

**Comment by thomasgafner** [comment] 2020-05-27 11:51
OK. To reproduce I use

schema-basic/src/schema-basic.js (there I add my 3 new node types)
demo/index.html (there I add example html using the 3 node types)
example-setup/src/keymap.js (there I register an Enter command doing the slice replace)

In detail:

in schema-basic.js insert

sym_tup_div: {
	content: "p_sym_tup_flow_normal p_sym_tup_flow_reverse",
	group: "block",
	defining: true,
	parseDOM: [{tag: "div.symmetry-tuple"}],
	toDOM() { return ["div", {class: "symmetry-tuple"}, 0] }
},
p_sym_tup_flow_normal: {
	content: "inline*",
	defining: true,
	parseDOM: [{tag: "p.flow-normal", context: "sym_tup_div/"	}],
	toDOM() { return ["p", {class: "flow-normal"}, 0] }
},
p_sym_tup_flow_reverse: {
	content: "inline*",
	defining: true,
	parseDOM: [{tag: "p.flow-reverse", context: "sym_tup_div/" }],
	toDOM() { return ["p", {class: "flow-reverse"}, 0] }
},

before the paragraph spec (line 14)

in demo/index.html insert 

`
< div class="symmetry-tuple">
	< p class='flow-normal'>Arem apsum dolor sit amet, sea graeci timeam antiopam an, eius ludus ad mei, et case efficiantur neglegentur pro.< / p>
	<  p class='flow-reverse'>An alitr ansequat quaerendum nec.< /p>
< /div>
`
Sorry I had to add extra spaces to the html example not to be interpreted by comment editor here.
I did that in line 42 (after the ol and p).

In example-setup/src/keymap.js (about line 85)
delete the bind("Enter" after the if (type = schema.nodes.list_item) { and insert before

if (type = schema.nodes.p_sym_tup_flow_normal) {
	bind("Enter", (state, dispatch) => {
		let doc = state.doc
		let selection = state.selection;
		let tr = state.tr;
		const srcSlc = doc.slice(selection.to, selection.$to.after(-1))
		tr = tr.replace(selection.from, selection.$to.after(-1), srcSlc)
		dispatch(tr.scrollIntoView())
		return true
	})
}

Then building the the two modules and running pm run demo, you can hit Enter within the flow-normal and get the TransformError: Invalid content for node sym_tup_div

Interesting: I tried something similar for the list_item ordered_list
but then it works.

Delete the if (type = schema.nodes.p_sym_tup_flow_normal) { and change the list_item code after like that:

if (type = schema.nodes.list_item) {
bind("Enter", (state, dispatch) => {
	let doc = state.doc
	let selection = state.selection;
	let tr = state.tr;
	const srcSlc = doc.slice(selection.to, selection.$to.after(-2))
	tr = tr.replace(selection.from, selection.$to.after(-2), srcSlc)
	dispatch(tr.scrollIntoView())
	return true
})

Here I have to use -2 index because there is an additional paragraph inside the li.

Somehow it seems to me that the replace algorithm works fine for a nested situation when there is no restriction on the number of nodes within a parent (an ol may have many li). But may be with the tuple example some steps during the replace temporarily create an invalid situation, which should not be checked at that moment, but only at the end of the whole replace step?

**Comment by thomasgafner** [comment] 2020-05-27 12:11
I tried, what happens if I define the schema without restriction: sym_tup_div: { content: "p_sym_tup_flow_normal p_sym_tup_flow_reverse+" (there is an additional plus sign) - so there may be one or more flow-reverse.
When I run that, there is no exception, but in the resulting dom there are two flow-reverse and I do not see where the first and empty one does come from. It should not be there and the document should remain the same as before.
I also tried to remove the defining: true from some or all of the 3 new node specs, but it does not matter.

**Comment by marijnh** [comment] 2020-06-03 08:07
Sorry, but this is still way too much context that you're pulling in. You don't need to edit files in the distribution to add nodes to a schema (you can create your own schema locally). If the problem is about calling `replace`, you should be able to reproduce this without involving a view or key bindings. You'll have to create a single, _minimal_, self-contained file, if you want me to look at this.

**Comment by thomasgafner** [comment] 2020-06-03 08:48
OK, I will try to do that.
I just thought showing it by modifying a few files in the distribution and run it in an 'environment' that comes with it will be fastest to reproduce. I certainly do not put my code there normally.
Maybe I better write a failing unit test.

**Comment by thomasgafner** [comment] 2020-06-03 11:24
The replace unit test is not such a good idea, since it also bases upon the schema-basic.js , which lacks a node definition with limited number of allowed child nodes - like the tuple example. When I add it, the 
2 of the 273 model/ tests fail:
DOMParser parse 
1) will create textblocks for block nodes
2) can parse marks at the start of defaulted textblocks

Additionally I had to also extend the test-builder for I could add my lopsided slice tests to test-replace.js and I guess all of that does not match your idea of being self-contained. - Even though it would save time and work at the end.
So I do it in a file. - But it is not fully clear to me under what conditions / env you are gonna run that file. I mean I have to import or require ProseMirror this way or that. - I try to do it in a file.

**Comment by thomasgafner** [comment] 2020-06-03 14:17
I put the code at the end of this comment into a self-contained file and run it with node file.js - and guess what: it just works. I cannot reproduce it there.

I output the the slice and did the same thing the way I described before - in the browser opening the demo page pushing enter. Before I adjusted the html and also the code that replaces the slice to be more like the code in the file. - And still it does not work.

The slice toString() it is the same for file and browser:
srcSlc <sym_tup_div(p_sym_tup_flow_normal("mal"), p_sym_tup_flow_reverse("reverse"))>(2,0)

From the slice you see, that for testing I cut it in the middle of the text nor|mal.

The adjusted html:
< p >paragraph before< / p >
< div class="symmetry-tuple" >
< p class='flow-normal'>normal< / p >
< p class='flow-reverse'>reverse< / p >
< / div >
< p >paragraph after< / p >
Like the code in the file the command (enter) now does:
const srcSlc = doc.slice(selection.to, selection.$to.after(-1))
console.log('srcSlc', srcSlc.toString())
tr = tr.replace(selection.to, selection.$to.after(-1), srcSlc)
This time I only use selection.to for it is less confusing to read what the code does.

Maybe one difference: In the file, the replace is on the doc Node but in the command on the tr Transform. Might that matter?

The contents of the file.js:

const {Schema, DOMParser} = require("prosemirror-model")

const testSchema = new Schema({
  nodes: {
		doc: {
			content: "block+"
		},
		p_sym_tup_flow_normal: {
			content: "inline*",
			defining: true,
			parseDOM: [{tag: "p.flow-normal",	context: "sym_tup_div/"	}],
			toDOM() { return ["p", {class: "flow-normal"}, 0] }
		},
		p_sym_tup_flow_reverse: {
			content: "inline*",
			defining: true,
			parseDOM: [{tag: "p.flow-reverse", context: "sym_tup_div/" }],
			toDOM() { return ["p", {class: "flow-reverse"}, 0] }
		},
		paragraph: {
			content: "inline*",
			group: "block",
			parseDOM: [{tag: "p"}],
			toDOM() { return ["p", 0] }
		},
		sym_tup_div: {
			content: "p_sym_tup_flow_normal p_sym_tup_flow_reverse",
			group: "block",
			defining: true,
			parseDOM: [{tag: "div.symmetry-tuple"}],
			toDOM() { return ["div", {class: "symmetry-tuple"}, 0] }
		},
		text: {
			group: "inline"
		}
	}
})

function main() {
	const sc = testSchema
	let doc = sc.node("doc", null, [
	  sc.node("paragraph", null, [sc.text("paragraph before")]),
	  sc.node("sym_tup_div", null, [
			sc.node("p_sym_tup_flow_normal", null, [sc.text("normal")]),
			sc.node("p_sym_tup_flow_reverse", null, [sc.text("reverse")])
		]),
	  sc.node("paragraph", null, [sc.text("paragraph after")])
	])
	const from = 23
	const $selPos = doc.resolve(from)
	const srcSlc = doc.slice(from, $selPos.after(-1))
	console.log(srcSlc.toString())
	doc.replace(from, $selPos.after(-1), srcSlc)
	console.log('ok')
}

main()

**Comment by marijnh** [comment] 2020-06-03 14:40
> Maybe one difference: In the file, the replace is on the doc Node but in the command on the tr Transform. Might that matter?

Yes, absolutely. You can create a `Transform` instance outside of an editor as well.

**Comment by thomasgafner** [comment] 2020-06-03 14:41
Then I try that too.

**Comment by thomasgafner** [comment] 2020-06-03 14:53
In the self-contained file.js I add
const {Transform} = require("prosemirror-transform")
then one line after creating the doc I add:
let tr = new Transform(doc)
and instead of doc.replace(..) I do
tr = tr.replace(from, $selPos.after(-1), srcSlc)

and it really makes a difference - I get the 
TransformError: Invalid content for node sym_tup_div

**Comment by thomasgafner** [comment] 2020-07-02 12:46
Does this correspond to your idea of self-containment or should I repeat the whole contents of the file.js with these few additional changes here?

**Comment by marijnh** [comment] 2020-07-08 13:38
> In the self-contained file.js I add

Did you edit your previous comment, or which file are we talking about? Could you just put it on https://gist.github.com/ or glitch.com or something, and point me at a coherent file that I can work from.

**Comment by thomasgafner** [comment] 2020-07-08 14:32
Just use the attached file [file.txt](https://github.com/ProseMirror/prosemirror/files/4891226/file.txt) or copy and paste the following code to an empty file.txt (I place it somewhere within the prosemirror dev env) and run it with the command "node file.txt", then you will see the error printed to the command line (no need for a browser):


const {Schema, DOMParser} = require("prosemirror-model")
const {Transform} = require("prosemirror-transform")

const testSchema = new Schema({
nodes: {
doc: {
content: "block+"
},
p_sym_tup_flow_normal: {
content: "inline*",
defining: true,
parseDOM: [{tag: "p.flow-normal", context: "sym_tup_div/" }],
toDOM() { return ["p", {class: "flow-normal"}, 0] }
},
p_sym_tup_flow_reverse: {
content: "inline*",
defining: true,
parseDOM: [{tag: "p.flow-reverse", context: "sym_tup_div/" }],
toDOM() { return ["p", {class: "flow-reverse"}, 0] }
},
paragraph: {
content: "inline*",
group: "block",
parseDOM: [{tag: "p"}],
toDOM() { return ["p", 0] }
},
sym_tup_div: {
content: "p_sym_tup_flow_normal p_sym_tup_flow_reverse",
group: "block",
defining: true,
parseDOM: [{tag: "div.symmetry-tuple"}],
toDOM() { return ["div", {class: "symmetry-tuple"}, 0] }
},
text: {
group: "inline"
}
}
})

function main() {
const sc = testSchema
let doc = sc.node("doc", null, [
sc.node("paragraph", null, [sc.text("paragraph before")]),
sc.node("sym_tup_div", null, [
sc.node("p_sym_tup_flow_normal", null, [sc.text("normal")]),
sc.node("p_sym_tup_flow_reverse", null, [sc.text("reverse")])
]),
sc.node("paragraph", null, [sc.text("paragraph after")])
])
let tr = new Transform(doc)
const from = 23
const $selPos = doc.resolve(from)
const srcSlc = doc.slice(from, $selPos.after(-1))
console.log(srcSlc.toString())
//doc.replace(from, $selPos.after(-1), srcSlc)
tr = tr.replace(from, $selPos.after(-1), srcSlc)
console.log('ok')
}

main()

**Comment by thomasgafner** [comment] 2020-07-08 14:38
or as [gist](https://gist.github.com/thomasgafner/1bf3afe0662ab805ef52abffb55c1f97.js) - seems not to be the same as an attachment

**Comment by marijnh** [comment] 2020-07-09 07:38
Thanks, that helps. Attached patch (released as prosemirror-transform 1.2.7) should fix this.

**Closed by marijnh** 2020-07-09 07:38 UTC

**Comment by thomasgafner** [comment] 2020-07-09 08:09
Thank you very much!
