### ISSUE TITLE
Unable to move cursor at start of an inline non-selectable node in Firefox

### ISSUE THREAD

**Issue by kepta** [ProseMirror/prosemirror#1220] opened 2021-11-18 03:55 UTC
To reproduce:
1. Visit this [fork](https://glitch.com/edit/#!/field-trusted-curler) of Dino example. 
2. I have updated the schema to make the Dino nodes `selectable=false`
3. Place cursor after the dino
4. Keep pressing left
5. You see that the cursor will just ignores the position before Dino and jumps to first line.

here is a video showcasing the problem:

https://user-images.githubusercontent.com/6966254/142348972-eadcd9f8-dc44-4b12-bf7c-87fd78085de7.mov

I checked that this only affects Firefox and not Chrome, Safari.

My Firefox version: 94.0.1

**Comment by kachkaev** [comment] 2022-01-20 22:32
Possible duplicate of https://github.com/ProseMirror/prosemirror/issues/1091?

**Closed** 2022-01-21 05:35 UTC
