### ISSUE TITLE
Many empty text nodes being created

### ISSUE THREAD

**Issue by davidye** [ProseMirror/prosemirror#561] opened 2017-02-15 05:49 UTC
An empty paragraph in the dom is:

`<p><br/></p>`

If type the character 'a' it becomes:

`<p>a</p>`

When I hit backspace it becomes:

`<p><br>""</p>`

Repeating this becomes...

`<p><br>""""""""</p>`

Doesn't really impact anything so not sure if this a bug or not? This was tested in chrome on the website.

**Comment by marijnh** [comment] 2017-02-15 09:42
It seems that Chrome (I couldn't reproduce this in Firefox) can get into a weird state where it doesn't report empty text nodes as child nodes of their parent node, but still shows them in the inspector. I.e. when I inspect such a node, it shows me a bunch of `""` children, but when I query `$0.lastChild` or `$0.childNodes.length`, it claims that it only has one child, the `<br>` node. This, I guess, is why ProseMirror isn't cleaning up these empty text nodes.

It appears this only happens in specific circumstances. If I try to reproduce it by manually adding empty text nodes to some node, they show up just fine in `childNodes`. **But**, if I create an editable, non-ProseMirror node and type/backspace a few times, I do see the phantom text nodes.

So this is a Chrome bug, and you should probably report it there. It might be possible for ProseMirror to find a kludge to remove these nodes, but since they don't seem to be causing any real harm, and you'd only get a lot of them in very specific situations, that may not be worth it.

**Comment by marijnh** [comment] 2017-08-17 07:49
Closing as being a browser bug that doesn't really impact the functioning of the editor.

**Closed by marijnh** 2017-08-17 07:49 UTC
