### ISSUE TITLE
Caret still invisible after hideselection removing from classes.

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [ProseMirror/prosemirror#958] opened 2019-07-24 21:56 UTC
For reproduce check gift:
https://github.com/scrumpy/tiptap/issues/405#issuecomment-514813824

Also image overflow caret.

Can be reproduced on prosemirror.net too.

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-07-24 21:57
@marijnh

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-07-24 22:10
Is that issue duplicate of https://github.com/ProseMirror/prosemirror/issues/958 ?

**Comment by marijnh** [comment] 2019-07-26 07:47
Can you condense your reproduction steps to a precise list of actions (in text, not screencast)? I can't understand the ones in the issue you linked.

**Comment by afwn90cj93201nixr2e1re** [comment] 2019-07-26 13:23
https://github.com/ProseMirror/prosemirror/issues/583#issuecomment-514819708

At site everything is described.

**Comment by marijnh** [comment] 2019-07-29 07:50
Right, I guess this is a duplicate of #583 then.

**Closed by marijnh** 2019-07-29 07:50 UTC
