### ISSUE TITLE
Caret does not appear when switching focus between two prosemirror editors embedded in the shadow root of custom elements

### ISSUE THREAD

**Issue by aduchate** [ProseMirror/prosemirror#1113] opened 2021-01-06 09:47 UTC
### Issue details

When you switch focus with the mouse between two prosemirror editors embedded in the shadow root of custom elements (created using lit-element but I'm not sure it is relevant), the caret is not displayed in the destination editor. The selection inside the PM is ok and when typing everything works as expected except for the missing caret.

If you click on the background of the window before clicking in the other PM. The caret appears.

### Steps to reproduce

`git clone https://github.com/aduchate/iqr-tf-test.git && cd iqr-tf-test && yarn install && npm run start`

connect to http://localhost:8080 under firefox (I tested using firefox 84)

### ProseMirror version

    "prosemirror-commands": "^1.1.4",
    "prosemirror-history": "^1.1.3",
    "prosemirror-keymap": "^1.1.4",
    "prosemirror-markdown": "^1.5.0",
    "prosemirror-model": "^1.13.1",
    "prosemirror-schema-basic": "^1.1.2",
    "prosemirror-schema-list": "^1.1.4",
    "prosemirror-state": "^1.3.3",
    "prosemirror-view": "^1.16.5"

### Affected platforms

This is a FF only issue

- [ ] Chrome
- [x] Firefox
- [ ] Internet Explorer
- [ ] Other

### Screenshots / Screencast (Optional)

https://user-images.githubusercontent.com/2221917/103754122-37be9a80-500c-11eb-9170-39fc7b55e6d0.mov

### Workaround

This plugin solves the problem

```
import { Plugin } from 'prosemirror-state'

export const caretFixPlugin = () => {
  let focusing = false
  return new Plugin({
    props: {
      handleDOMEvents: {
        focus: view => {
          if (focusing) { focusing = false } else {
            focusing = true
            setTimeout(() => { view.dom.blur(); view.dom.focus() },0)
          }
          return false
        }
      }
    }
  })
}
```

**Comment by marijnh** [comment] 2021-01-06 13:53
This reproduces with the tiny, ProseMirror-less code below, so it's definitely a Firefox bug. I've filed [an issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1685300), though those don't tend to be looked at very quickly.

Since this is a browser but, in an uncommon situation, that you've found a workaround for, I don't think it is worthwhile to add a kludge for this to ProseMirror itself. Hopefully it'll be fixed in the browser at some point, and other people running into it find this issue.

```html
<!doctype html><meta charset=utf8>
<div style="background: orange"></div>
<script>
  document.querySelector("div").attachShadow({mode: "open"}).innerHTML =
    "<div contenteditable=true>One</div><hr><div contenteditable=true>Two</div>"
</script>
```

**Closed by marijnh** 2021-01-06 13:53 UTC

**Comment by kelunik** [comment] 2022-03-04 10:32
I'd like to note that this also happens with every other active form field before focusing, e.g. if there's a button in the shadow DOM that opens a popover, and the popover contains the editor, focusing with a working cursor won't work until the focus of the button is lost first, e.g. by clicking somewhere else.

**Comment by sshanzel** [comment] 2022-06-14 08:11
> I'd like to note that this also happens with every other active form field before focusing, e.g. if there's a button in the shadow DOM that opens a popover, and the popover contains the editor, focusing with a working cursor won't work until the focus of the button is lost first, e.g. by clicking somewhere else.

Have you found a workaround for this? I tried focusing after mounting the popover and doesn't seem to do the trick. Even tried to blur the document's current active element.

**Comment by kelunik** [comment] 2022-06-14 08:54
@sshanzel We're using the workaround mentioned in the initial post here without problems.
