### ISSUE TITLE
Uncaught RangeError occur when typing a korean always.

### ISSUE THREAD

**Issue by bitmapdata** [ProseMirror/prosemirror#458] opened 2016-09-26 10:01 UTC
![ezgif-3689113548](https://cloud.githubusercontent.com/assets/3241312/18829871/5197a38e-8419-11e6-9724-3dc48736718e.gif)

My Environment: OS X El Capitan, Chrome Ver. 53.0.2785.116

Is the same Safari(9.1.1), Opera(39.0.2256.71), Firefox(49.0.1).

Definitely previous version (0.10.x) did not have this issue.

**Comment by marijnh** [comment] 2016-09-26 20:40
I wasn't able to reproduce the issue you showed (maybe because of Linux IME behaving differently from OS X), but I ran into a similar problem that might be a manifestation of the same bug. Does attached patch help for you?

**Comment by bitmapdata** [comment] 2016-09-26 21:50
Nope. 

![ezgif-566434831](https://cloud.githubusercontent.com/assets/3241312/18852945/c3dd8a76-847d-11e6-81c2-b2b6e163915a.gif)

As you can see, sometimes hangul combined vowels is separated unpredictable.

correctly following.

1. 안녕하세요.
2. 만나서반갑습니다.
3. 한글테스트중입니다.
4. 한글조합이깨집니다.

**Comment by marijnh** [comment] 2016-09-27 07:45
The problem is I *can't* really see what is going on, since as a non-Korean speaker, I have no idea what you are typing, or what the expected behavior is. Could you break down what you are doing in a way that I might be able to follow? I.e. which keys are you pressing, in which order, when the error occurs.

**Comment by bitmapdata** [comment] 2016-09-27 15:32
Described below about first eg. (The remaining examples are also the same issue.)

1. switch to Korean mode (cmd + space)

2. When typing in the following order 'ㅇ' -> 'ㅏ' -> 'ㄴ' -> 'ㄴ' -> 'ㅕ' -> 'ㅇ' -> 'ㅎ' -> 'ㅏ' -> 'ㅅ' -> 'ㅔ' -> 'ㅇ' -> 'ㅛ'  must be shown to '안녕하세요'. but '안ㄴㅕㅇ하세ㅇㅛ'.

Typing: 'ㅇ' -> 'ㅏ' -> 'ㄴ' -> 'ㄴ' -> 'ㅕ' -> 'ㅇ' -> 'ㅎ' -> 'ㅏ' -> 'ㅅ' -> 'ㅔ' -> 'ㅇ' -> 'ㅛ'

Expected shown to combined: 'ㅇ' -> '아' -> '안' -> '안ㄴ' -> '안녀' -> '안녕' -> '안녕ㅎ' -> '안녕하' -> '안녕핫'-> '안녕하세' -> '안녕하셍' -> '안녕하세요'

Incorret combined: 'ㅇ' -> '아' -> '안' -> '안ㄴ' -> '안ㄴㅕ' -> '안ㄴㅕㅇ' -> '안ㄴㅕㅇㅎ' -> '안ㄴㅕㅇ하' -> '안ㄴㅕㅇ핫'-> '안ㄴㅕ하세' -> '안ㄴㅕ하세ㅇ' -> '안ㄴㅕ하세ㅇㅛ'

When typing the korean compositionStart, compositionUpdate, compositionEnd is activated until the finished. In my opinion get interrupted while the process is running combining characters korean.

[0236ff4](https://github.com/ProseMirror/prosemirror-view/commit/0236ff456edb0905d71a69e09c271d511766f3c6) version log
problem
![screen shot 2016-09-27 at 11 52 04 pm](https://cloud.githubusercontent.com/assets/3241312/18878917/619681f2-850d-11e6-8a42-2c2e11d197e2.png)

0.10.1 version log
No problem
![screen shot 2016-09-28 at 12 01 55 am](https://cloud.githubusercontent.com/assets/3241312/18879338/d70a3ea0-850e-11e6-9dc5-2b2ef015ed13.png)

**Comment by marijnh** [comment] 2016-09-27 15:40
> When typing in the following order

Is it possible to do this on a latin keyboard? If so, what latin letters must be typed?

**Comment by bitmapdata** [comment] 2016-09-27 15:53
Korean Keyboard: 'ㅇ' -> 'ㅏ' -> 'ㄴ' -> 'ㄴ' -> 'ㅕ' -> 'ㅇ' -> 'ㅎ' -> 'ㅏ' -> 'ㅅ' -> 'ㅔ' -> 'ㅇ' -> 'ㅛ'
Latin Keyboard:     'd' ->  'k' ->  's'  ->  's' ->  'u' -> 'd' ->  'g' ->   'k' ->  't' ->  'p' -> 'd'  ->  'y'

**Comment by marijnh** [comment] 2016-10-24 11:08
I still wasn't able to reproduce this on Linux or Windows. I don't have an OS X machine to test on.

Could you, if it's still happening on prosemirror.net now (the demos run 0.12.0 now), paste a backtrace from the errors?

**Comment by marijnh** [comment] 2016-12-01 22:18
There has been some more work on the way composition events are handled. Any chance you can see what the status is with release 0.14?

**Comment by marijnh** [comment] 2016-12-09 12:55
Closing on the assumption that recent changes have fixed this or at least made the problem a different one. Feel free to add information if it still occurs and you can help me reproduce it.

**Closed by marijnh** 2016-12-09 12:55 UTC
