### ISSUE TITLE
Undoing and redoing a list item lift, behaves incorrectly when collab module is active

### ISSUE THREAD

**Issue by kiejo** [ProseMirror/prosemirror#297] opened 2016-04-11 10:14 UTC
I used the same `demo.js` as in #294:
```javascript
var ProseMirror = require("../dist/edit/main").ProseMirror
require("../dist/inputrules/autoinput")
require("../dist/collab")

var pm = window.pm = new ProseMirror({
  place: document.querySelector(".full"),
  autoInput: true,
  collab: {version: 0}
})
```
Here's a recording of what goes wrong. After lifting the second list item, I pressed undo three times and then redo three times:
![bullets_2](https://cloud.githubusercontent.com/assets/152507/14423911/8e16534c-ffde-11e5-810e-4475e78bc676.gif)

**Comment by marijnh** [comment] 2016-04-11 12:06
Are you including patch efeb4d807ec205 when you reproduce this? I am not able to reproduce it with that patch.

**Comment by kiejo** [comment] 2016-04-11 12:39
Yes, I am using the latest master to reproduce this (I can't reproduce #294 with this version).
It's important to press undo three times before pressing redo three times. I used `Ctrl+]` and `Ctrl+[` for the sinking and lifting. As with the other issue, I can only reproduce this with the `collab` module active.

**Comment by marijnh** [comment] 2016-04-11 12:58
Ah, you lifted the items at one point. (In general, I much prefer textual descriptions of actions to videos, since it's really easy to misinterpret of miss some aspect of a video.) (Even better would be a failing test case.)

I'll investigate.

**Comment by kiejo** [comment] 2016-04-11 13:09
Alright, I'll keep that in mind when raising new issues in the future!

**Comment by marijnh** [comment] 2016-04-11 14:10
This uncovered another obscure bug. Fixed by attached patch. Thanks!

**Closed** 2016-04-11 14:10 UTC
