### ISSUE TITLE
When dragging and dropping inline images, show a cursor for exact destination while dropping 

### ISSUE THREAD

**Issue by mohsen1** [ProseMirror/prosemirror#12] opened 2015-09-02 23:17 UTC
![screen shot 2015-09-02 at 4 16 24 pm 2](https://cloud.githubusercontent.com/assets/543633/9647028/0613d770-518e-11e5-9a8f-0bd576565a89.png)

**Comment by marijnh** [comment] 2015-09-03 07:56
Yep, duplicate of #1

**Closed by marijnh** 2015-09-03 07:56 UTC
