### ISSUE TITLE
Cursor jumps to the right of a word after pressing enter on Android

### ISSUE THREAD

**Issue by jljorgenson18** [ProseMirror/prosemirror#1181] opened 2021-06-10 20:59 UTC
### Issue details

When putting your cursor to the left of a word and hitting enter to create a new paragraph, on Android the cursor will jump to the right of the word

### Steps to reproduce

1. Open up Prosemirror on Android device
2. Add a paragraph of text
3. Place cursor at the beginning of a word in that paragraph
4. Hit enter

Expected Result:
Cursor is to the left of the word on the new paragraph

Actual Result:
Cursor is to the right of the word on the next paragraph

### ProseMirror version

prosemirror-view: 1.18.7

### Affected platforms

- [x] Android

### Screenshots / Screencast (Optional)

https://user-images.githubusercontent.com/5751354/121596197-c47ae380-ca04-11eb-984f-0945d7c0dc2f.mp4

Note: Issue was reported here https://discuss.prosemirror.net/t/contenteditable-on-android-is-the-absolute-worst/3810/6

**Comment by marijnh** [comment] 2021-12-09 15:02
Oh, nice. The browser that refuses to fire proper keydown events does, in these very specific circumstances (note that you really have to type the paragraph _right before_ pressing enter in it, otherwise this doesn't reproduce), fire a regular keydown event, with the keycode for enter. But it does that between a flurry of superfluous composition changes (first deleting the word after the cursor, then the space before it, then comes the enter event, and then the word is reinserted again) which end up confusing ProseMirror.

Still looking for a workaround. The precise sequence of events appears to be unpredictable/timing dependent, so it's kind of hard to predict when the browser is done doing its thing (and waiting too long harms responsiveness).

**Comment by marijnh** [comment] 2021-12-10 12:22
Attached patch addresses this case in CodeMirror. Trying to land something similar in ProseMirror.

**Comment by marijnh** [comment] 2021-12-10 14:17
And the other attached patch does something similar for ProseMirror.

**Comment by jljorgenson18** [comment] 2021-12-10 14:59
We were somehow able to work around this issue already ourselves but I wasn't quite sure how. I think I did something with the markCursor to not remove it if it's at a certain point in the composition.

As far as Prosemirror goes, I'm worried about this line

```
if (browser.android && browser.chrome && event.keyCode == 13) return
```

because certain Android keyboards (e.g. Samsung) actually do consistently emit enter keys, even when a composition is not active. You also can easily emit enter keys if you use a bluetooth keyboard (which is especially relevant for tablets).

**Comment by marijnh** [comment] 2021-12-10 15:10
The library should still pick up the enter press from the DOM changes, but yeah, that is going to allow more possibilities for things to go wrong. I'm not sure how to cleanly detect this problematic situation there to only avoid synchronous handling when necessary. Any ideas?

**Comment by jljorgenson18** [comment] 2021-12-10 17:50
Does the Prosemirror demo take the absolute latest from Prosemirror-view or the latest marked version? I'm not seeing the issue anymore in the Prosemirror demo.

**Comment by jljorgenson18** [comment] 2021-12-10 18:02
Not entirely sure if this helps but we have this bit of logic in our android input plugin inside of the view->update section

```ts
                    const hasCursorWrapper = Boolean(view.cursorWrapper);
                    if (prevHasCursorWrapper !== hasCursorWrapper) {
                        prevHasCursorWrapper = hasCursorWrapper;
                        // When the cursor wrapper disappears, sometimes the selection
                        // jumps a bit if a composition restarts. Suppress selection updates momentarily
                        if (!hasCursorWrapper) {
                            (view as any).domObserver.suppressSelectionUpdates();
                        }
                    }
```

Although I'm not entirely sure if the cursor wrapper is playing a role in this scenario.

**Comment by marijnh** [comment] 2021-12-12 12:33
The demo should be showing the latest releases, not the git branch. The hack there seems like it is targeting another issue, since I don't think there'll be cursor wrappers involved in this one.

**Comment by jljorgenson18** [comment] 2021-12-12 15:50
I can't seem to reproduce it on my new Pixel 6 on Android 12.
 https://user-images.githubusercontent.com/5751354/145719260-cdf7c2fd-69da-4402-bf7a-a38d1f67fa2f.mp4

I could try it again on my older phone. What are you using for tests?

**Comment by max-nextcloud** [comment] 2022-06-23 09:52
[cc0934e](https://github.com/ProseMirror/prosemirror-view/commit/cc0934ed0735cc8f0fb31d90f46b0368c2b83a09) seems to have made it into master. So the main part of this issue should be fixed.
I understand that there may be other problems when using external keyboards but there's no concrete case of that right now.

What's missing to close this issue?

**Comment by marijnh** [comment] 2022-06-23 11:27
Nothing, just forgotten I guess.

**Closed by marijnh** 2022-06-23 11:27 UTC

**Comment by wbharding** [comment] 2022-12-12 18:16
Since the issue didn't repro on Pixel 6 / Android 12, I wonder if this hack could be removed? It is currently causing headaches for us when we press "Enter" from a GapCursor at the end of a document. In this case, the early return from `keyDown` handler means that the "Enter" press doesn't get sent to our keymap bindings for "Enter" that are invoked here on every other platform. In turn, PM ends up inserting a `<p>\r</p>` at the end of the document, which can't be tapped, so the user can never tap to anywhere in the document after the bogus element that Chrome inserts:

![](https://images.amplenote.com/31fcc296-52ff-11ed-9b12-12df968fac61/e89e1550-fa8d-4f3a-8e47-f37fcb933ae5.jpg)

It would be nice to know that our "Enter" keymap bindings will work regardless of platform, which seems like can not be so while this hack exists, so if it doesn't repro anymore it would be nice to remove. 

I haven't precisely determined why the enter keymap binding _does_ work on Android Chrome when pressed from a non-GapCursor location. It seems that in those cases DOMObserver.observer simulates an "enter" press upon seeing a complicated combination of selection attributes:

![](https://images.amplenote.com/31fcc296-52ff-11ed-9b12-12df968fac61/281233bc-e13a-4bfe-af1a-8482c57fbdf3.jpg)

My best guess is that the keypress event from the view gets "handled" before the DOMObserver.observer can read about a DOM change.

**Comment by marijnh** [comment] 2022-12-16 08:45
> Since the issue didn't repro on Pixel 6 / Android 12, I wonder if this hack could be removed?

I think that comment was post-patch, so no, that won't help.

Attached patch should improve the behavior in this situation. (Next time, unless you're 100% sure the old issue is in fact related, prefer opening a new issue.)

**Comment by wbharding** [comment] 2022-12-16 16:45
Thanks for the quick attention on this, and for doing the recon on a solution! Really appreciate your efforts 🙏 

> Next time, unless you're 100% sure the old issue is in fact related, prefer opening a new issue.

I can understand why this would be the preference, so sorry about dragging this issue into a new round of commits. The reason it felt necessary to post here was because our internal solution for our problem was [to specifically comment a single line from the original fix](https://github.com/ProseMirror/prosemirror-view/commit/cc0934ed0735cc8f0fb31d90f46b0368c2b83a09):

```
// if (browser.android && browser.chrome && event.keyCode == 13) return
```

By removing that line, we get back keybindings on Enter press in GapCursor on Android Chrome, bringing its behavior in line with all other platforms (+ simplifying debugging). We made the change to remove that line a few days ago and released it to our ~3,000 daily users and have yet to hear any report of a misplaced cursor after pressing enter in a paragraph (the original issue here). I have also tried and failed to repro that issue on my Android device.

> I think that comment was post-patch

Your patch was December 10th and his comment mentioning inability to repro came December 12th. If I'm correctly interpreting your comment above ("The demo should be showing the latest releases, not the git branch"), the demo site updates whenever a new release of PM is made. The [next release after December 10 looks to have been 1.23.4, released December 22](https://github.com/ProseMirror/prosemirror-view/releases/tag/1.23.4).

All things being equal, I'd prefer removing a line that creates platform-specific behavior (= more debug difficulty), vs. adding a few more lines of platform-specific handling. Maybe we could wait awhile and see whether anyone is able to observe this ticket's original bug after we removed the line above? If we don't hear any such reports for a few weeks, do you think it might be preferable to just remove that line vs. adding the more recent platform-specific handlers?

**Comment by marijnh** [comment] 2022-12-16 17:56
I have recently worked on this very issue in the CodeMirror codebase, so I'm rather sure it still exists with current GBoard implementation.
