### ISSUE TITLE
Mod-shift bindings aren't firing on Chrome OSX

### ISSUE THREAD

**Issue by FelipeTaiarol** [ProseMirror/prosemirror#762] opened 2018-02-12 15:40 UTC
Tested: Mod-Shift-z, Mod-Shift-u

**Comment by marijnh** [comment] 2018-02-13 15:00
This turned out to be a duplicate of #715, solved by upgrading to the latest w3c-keyname package

**Closed by marijnh** 2018-02-13 15:00 UTC
