### ISSUE TITLE
Native toolbar overlaps prosemirror menubar on Mobile Safari

### ISSUE THREAD

**Issue by krasnoukhov** [ProseMirror/prosemirror#312] opened 2016-04-20 11:17 UTC
Platform: Safari on iOS 9.3
How to reproduce:

1. Select some text on a first line

Not sure if this is prosemirror problem, but maybe you have some suggestions how to address that?

Screenshot: http://take.ms/8RqYA

**Comment by marijnh** [comment] 2016-04-20 11:23
Duplicate of #7

**Closed by marijnh** 2016-04-20 11:23 UTC

**Comment by krasnoukhov** [comment] 2016-04-20 11:26
Oops, sorry!
