### ISSUE TITLE
Paste within empty quote or list item removes that node

### ISSUE THREAD

**Issue by wes-r** [ProseMirror/prosemirror#411] opened 2016-07-21 14:36 UTC
Tested on http://prosemirror.net/demo/basic.html

Pasting simple text into an empty list item or empty quote will knock you out of the list item or the quote.

E.g:
```
* item 1
* item 2
* <paste "hello world" here>
```

results in:
```
* item 1
* item 2
hello world
```

https://github.com/ProseMirror/prosemirror/blob/master/src/edit/input.js#L434 is the offending line that deprecates the `from` position.

**Comment by marijnh** [comment] 2016-07-21 20:01
Duplicate of #397

**Closed by marijnh** 2016-07-21 20:01 UTC
