### ISSUE TITLE
[prosemirror-view] Cursoring through widget in FF broken

### ISSUE THREAD

**Issue by RichieAHB** [ProseMirror/prosemirror#832] opened 2018-08-06 19:47 UTC
### Issue details

Cursoring left through a widget decoration will cause a selection immediately either side of the decoration. I feel like this one had been raised already but I couldn't find it.

### Steps to reproduce

Cursor left through the red square root signs in:

https://glitch.com/edit/#!/understood-canidae

### ProseMirror version

Prosemirror view as on glitch.com (1.4.2?)

### Affected platforms

FF v62

- [ ] Chrome
- [x] Firefox
- [ ] Internet Explorer
- [ ] Other

### Screenshots / Screencast (Optional)

![pm-deco-ff](https://user-images.githubusercontent.com/1652187/43737569-a7ff17b8-99b9-11e8-9687-2ffdc97379ec.gif)

**Comment by RichieAHB** [comment] 2018-08-07 11:47
The issue goes away with the below patch but it's proving pretty hard to test:

```diff
diff --git a/src/capturekeys.js b/src/capturekeys.js
index 6db9678..d0c7c7a 100644
--- a/src/capturekeys.js
+++ b/src/capturekeys.js
@@ -97,7 +97,32 @@ function skipIgnoredNodesLeft(view) {
     }
   }
   if (force) setSelFocus(view, sel, node, offset)
-  else if (moveNode) setSelFocus(view, sel, moveNode, moveOffset)
+  else if (moveNode) {
+    if (browser.gecko) {
+      // Get around FF setting bad selection around widget
+      // go to the closest matching parent node with a prev node
+      // and dig back down to select the end of the lowest node
+
+      while (moveOffset === 0 && moveNode !== view.dom) {
+        moveNode = moveNode.parentNode
+        moveOffset = domIndex(moveNode)
+      }
+      
+      if (moveNode.childNodes.length) {
+        moveNode = moveNode.childNodes[moveOffset - 1]
+      }
+  
+      while (moveNode.lastChild) {
+        moveNode = moveNode.lastChild
+      }
+  
+      moveOffset = moveNode.nodeType === 3
+        ? moveNode.nodeValue.length
+        : moveNode.childNodes.length
+    }
+
+    setSelFocus(view, sel, moveNode, moveOffset)
+  }
 }
 
 // Make sure the cursor isn't directly before one or more ignored
```

**Comment by marijnh** [comment] 2018-08-13 12:36
The patch seems _very_ special-cased. Could you try if patches 174b0dc0686ca6922c50f5e9b14113f30333fab4 and 0c6a4080fe4a9d060ce534ed796bca350371591f also work for you?

**Comment by RichieAHB** [comment] 2018-08-21 15:19
It does work when the widget has some innerHTML but doesn't work when there is a pseudo element in the item. For my purposes I can use innerHTML but worth mentioning: https://glitch.com/edit/#!/capricious-trader

**Comment by marijnh** [comment] 2018-08-24 15:13
Does attached patch help with the behavior for pseudo-element widgets?

**Comment by RichieAHB** [comment] 2018-08-24 16:44
Yes it works in terms of the cursoring, although the selection ends up _inside_ the pseudo element which means I needed to alter my styling of the pseudo element - which is fine in this case - as the cursor was moving upward due to `line-height` styles inside the element. Also, the cursor changes to the colour of the text (which is why I think the selection is inside) but this again can be solved using `caret-color: inherit;`. I thought the selection inside was probably worthy of note but I can definitely get where I need to with that patch thank you!

In the course of this I've noticed that when going _forward_ with `Shift+RightArrow` to create a selection, the same problem happens in FF where the cursor sticks for a keypress. When I get time next week I'm happy to look through and see if I can find similar patches for _rightward_ selections as you've added here - sorry to have to mention another browser related bug 😞

**Comment by dlants** [comment] 2019-03-11 19:20
I am running into an issue here with FF:

On this line:

```
// Gecko will do odd things when the selection is directly in front
// of a non-editable node, so in that case, move it into the next
// node if possible. Issue prosemirror/prosemirror#832.
if (result.gecko && node.nodeType == 1 && offset < nodeLen(node) && isIgnorable(node.childNodes[offset])) { force = true; }
```

I am getting an error:

```
 Error: Permission denied to access property "nodeType"
    skipIgnoredNodesLeft
    captureKeyDown
    keydown
    event
```

I'm on FF 66.0b12 (64-bit), using `prosemirror-view` `1.8.3`.

**Comment by marijnh** [comment] 2019-03-12 09:45
@dlants Could you open a separate issue for that, and include more information on when it happens, preferably with a way to reproduce it?

**Comment by marijnh** [comment] 2020-03-18 17:00
Is this still happening? (I can't access the glitch link anymore, sorry.)

**Comment by RichieAHB** [comment] 2020-03-20 17:14
It is still happening and (I'm not sure if this was the case when opening the issue), if you type at that position:

- Everything after the last decoration of its kind is removed
- The cursor jumps to the first widget of it's kind and starts typing there
- Following that, if you undo from this position, the deleted text is reinserted but the added text is not removed.

FYI, I can still view that glitch link 🤷‍♂ 

Hope that helps but I know these bugs are very browser dependent and fiddly 😞

**Comment by marijnh** [comment] 2020-05-01 11:37
Today, when I try to access the glitch link I get "Due to our project quota limits, this app cannot run". We might need to reconsider the suitability of glitch for this kind of stuff. I tried to reproduce what you might be doing from the screenshot (just having some inline widgets in a paragraph, mapping them along with content changes), but I wasn't able to reproduce the problem like that.

**Comment by RichieAHB** [comment] 2020-05-04 06:44
I can actually still click “remix” to fork the glitch in its current state when that modal appears saying the owner has too many projects. This is the new link (although haven’t been able to test as on mobile) https://glitch.com/edit/#!/uneven-power-walker?path=index.js%3A1%3A0

**Comment by marijnh** [comment] 2020-05-04 08:35
I can open the glitch link now. But unfortunately, I'm not sure anymore what the problem we were looking at is. Your message from March describes issues with typing at "that position", which I assume is the widget position, but I'm not seeing them. Could you describe the entire problem and reproduction instructions once more?

**Comment by RichieAHB** [comment] 2020-05-04 09:10
Sorry, by "that position" I meant the single position around a decoration that is (erroneously) accessible when cursoring _left_ and that (correctly) isn't accessible when cursoring _right_, i.e. the invalid position on one side of the widget decoration. That said I don't actually seem to be able to replicate it a month later (on FF 75) 🤷 ... the only issue I see now is that the cursor appears on the left side of a decoration when cursoring right through it (`𐌆` represents the cursor):

`my text 𐌆[decoration] my text` - cursor appears to the left of the decoration
`my text [decoration]new text𐌆 my text` - new input appears to the right of the decoration

That said, this is much more minor and there might be an issue for this already but thought it's probably worth highlighting.

**Comment by marijnh** [comment] 2020-05-04 09:27
> That said I don't actually seem to be able to replicate it a month later (on FF 75)

Hah, that explains my confusion.

I think the fact that the input appears on the right of the decoration is related to the fact that you're not mapping the decorations.

**Comment by RichieAHB** [comment] 2020-05-04 09:55
Ah yeah, that definitely seems to be true. Sorry, I haven’t touched a PM
codebase in over a year so a bit rusty!

**Comment by marijnh** [comment] 2020-05-04 09:58
Yeah, sorry for leaving this sitting for so long. Going to close it, if further related things come up let's open a specific issue.

**Closed by marijnh** 2020-05-04 09:58 UTC
