### ISSUE TITLE
Safari: selecting across a custom node from the bottom interrupts the selection / moves it into the node.

### ISSUE THREAD

**Issue by mhuebert** [ProseMirror/prosemirror#1315] opened 2022-09-28 08:49 UTC
In Safari (but not Chrome or Firefox), when dragging a selection into a custom node from the bottom, the selection moves fully into the custom node (removing the outer selection entirely and preventing one from continuing to expand the selection). This is reproducible on the ProseMirror embedded editor example: https://prosemirror.net/examples/codemirror/. Dragging a selection across the node from the top works as expected.

Video:

https://user-images.githubusercontent.com/165223/192731480-b66796cc-f9b9-4333-9589-47ec5f669db7.mov

I've tested on Chrome (105.0.5195.125), Firefox (103.0.2) and Safari (16.0 as well as unknown previous version, I upgraded during testing and the problem persisted). `prosemirror-view` 1.27.2.

**Comment by marijnh** [comment] 2023-06-19 13:35
This seems to be a Safari issue—selecting this way moves the focus into the inner editable element, which stops further mouse selection inside the outer editor. It can be reproduced without ProseMirror by wrapping to contenteditable elements (with a non-editable wrapper around the inner one). As such, I don't think this can be fixed in the library.

**Closed by marijnh** 2023-06-19 13:35 UTC
