### ISSUE TITLE
Firefox: ⌘-A select all not working

### ISSUE THREAD

**Issue by forresto** [ProseMirror/prosemirror#282] opened 2016-03-28 19:18 UTC
On http://prosemirror.net/, focus editable and press ⌘-A. Selection flashes and caret ends up at end of editable.

Expected: editable is all selected

**Comment by marijnh** [comment] 2016-03-28 20:39
I think this is fixed in 0.5.0 (the demo is on an older version) and in master. Could you check?

**Comment by marijnh** [comment] 2016-03-28 21:16
(I've just updated the demo pages to the current code.)

**Comment by forresto** [comment] 2016-03-29 03:08
I'm seeing same bug on prosemirror.net and our own app with 0.5.1.

**Comment by marijnh** [comment] 2016-03-29 14:15
I booted my Mac, but could not reproduce the issue on current prosemirror.net (which runs yesterday's git code)

**Comment by marijnh** [comment] 2016-03-29 14:20
Oh, I missed the part where it says 'Firefox' in the issue title. I _can_ reproduce in Firefox. Will look into it.

**Comment by marijnh** [comment] 2016-03-29 14:29
Attached patch should help.

**Closed** 2016-03-29 14:29 UTC
