### ISSUE TITLE
html paste stopped working

### ISSUE THREAD

**Issue by johanneswilm** [ProseMirror/prosemirror#347] opened 2016-05-12 13:21 UTC
Steps to re[produce:

1. Copy arbitrary html from website
2. Paste into ProseMirror instance (pre-0.7.0)

Expected behavior: pasting of content.

Observed behavior: No visual change, but steps are produced.

This used to work until yesterday.

**Comment by marijnh** [comment] 2016-05-12 13:43
What does pre-0.7.0 mean? In the demo on the current master branch, I can paste HTML just fine.

**Comment by johanneswilm** [comment] 2016-05-12 13:48
"pre-0.7.0" - current master branch version. 

I see no error message produce. There is just no new content in the resulting doc. Pasting plain text works fine. Our paste filter has been turned off. I will try with demo...

**Comment by johanneswilm** [comment] 2016-05-12 14:19
Demo does work. Probably has to do with the schema definition... looking further.

**Comment by johanneswilm** [comment] 2016-05-12 14:55
@marijnh This seems to have something to do with the schema declaration. When pasting html text, this seems to be transformed using fromDom. Any restrictions on the top-level doc-element seem to be transferred to the pasted content. So in our case, where the schema says 
```
doc: {type: Doc, content: "title subtitle authors abstract keywords body"},
title: {type: Title, content: "text*"},
[...]
```

It seems to try to create a new doc instance (slice) with those six elements and then insert the to be pasted content into the first subelement (the title element), which happens not to accept HTML.  I haven't debugged it further than this, as I assume you can see what is going on already. But please let me know if you want me to look further into this.

**Comment by marijnh** [comment] 2016-05-12 14:58
Ahh, that makes sense. This is a duplicate of #342 in that case.

**Closed by marijnh** 2016-05-12 14:58 UTC
