### ISSUE TITLE
inline code blocks escaped in prosemirror-markdown

### ISSUE THREAD

**Issue by mhuebert** [ProseMirror/prosemirror#694] opened 2017-09-03 19:12 UTC
Each time text marked with `inline-code` is round-tripped (serialized & deserialized), it is escaped, so eg. `[]` becomes `\[\]` becomes `\\\[\\\\]` and so on. I made the following gif on the [example page](http://prosemirror.net/examples/markdown/):

![pm sep-03-2017 21-06-15](https://user-images.githubusercontent.com/165223/30005848-dd76dd0e-90eb-11e7-8d9a-157c3c16909c.gif)

**Comment by marijnh** [comment] 2017-09-03 19:20
This is a duplicate of https://github.com/ProseMirror/prosemirror-markdown/issues/3

**Closed by marijnh** 2017-09-03 19:20 UTC
